server:
  port: 2007
  servlet:
    context-path: /api-webService

spring:
  datasource:
    name: ${DB_NAME:agri_senegal}
    host: ${DB_HOST:127.0.0.1}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:passer}

    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${spring.datasource.host}:5432/${spring.datasource.name}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: projet
  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

#      cors:
#        allowed-origins: "http://localhost:4200,http://localhost:4500"
#        allowed-methods: "*"
#        allowed-headers: "*"
#        exposed-headers: "Authorization,Link"
#        allow-credentials: true
#        max-age: 1800
